### ISSUE TITLE
openshift: TriggerTemplate is not namespace independent

### ISSUE THREAD

**Issue by raballew** [raballew/hello-world#5]
In https://github.com/raballew/spring-boot-hello-world/blob/master/environments/openshift/05-trigger.yaml the TriggerTemplate uses a image resource with an URL dependent on the namespace where the TriggerTemplate is deployed.

```
          - name: build-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: image-registry.openshift-image-registry.svc:5000/hello-world/$(params.gitrepositoryname):$(params.gitrepositorybranchname)
```

This might cause trouble if the resources are deployed in a different namespace and access permission to the registry are not set correctly.

Goal should be to remove `hello-world` and replace it with `.metadata.namespace`.
